// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Vla8islav/gophprofile/internal/domain (interfaces: GophprofileRepository,GophprofileService)
//
// Generated by this command:
//
//	mockgen -destination=domain_mock.go -package=mocks github.com/Vla8islav/gophprofile/internal/domain GophprofileRepository,GophprofileService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Vla8islav/gophprofile/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGophprofileRepository is a mock of GophprofileRepository interface.
type MockGophprofileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGophprofileRepositoryMockRecorder
	isgomock struct{}
}

// MockGophprofileRepositoryMockRecorder is the mock recorder for MockGophprofileRepository.
type MockGophprofileRepositoryMockRecorder struct {
	mock *MockGophprofileRepository
}

// NewMockGophprofileRepository creates a new mock instance.
func NewMockGophprofileRepository(ctrl *gomock.Controller) *MockGophprofileRepository {
	mock := &MockGophprofileRepository{ctrl: ctrl}
	mock.recorder = &MockGophprofileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophprofileRepository) EXPECT() *MockGophprofileRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockGophprofileRepository) CreateUser(ctx context.Context, user domain.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophprofileRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophprofileRepository)(nil).CreateUser), ctx, user)
}

// GetUserByLogin mocks base method.
func (m *MockGophprofileRepository) GetUserByLogin(ctx context.Context, login string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockGophprofileRepositoryMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockGophprofileRepository)(nil).GetUserByLogin), ctx, login)
}

// Ping mocks base method.
func (m *MockGophprofileRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophprofileRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophprofileRepository)(nil).Ping), ctx)
}

// MockGophprofileService is a mock of GophprofileService interface.
type MockGophprofileService struct {
	ctrl     *gomock.Controller
	recorder *MockGophprofileServiceMockRecorder
	isgomock struct{}
}

// MockGophprofileServiceMockRecorder is the mock recorder for MockGophprofileService.
type MockGophprofileServiceMockRecorder struct {
	mock *MockGophprofileService
}

// NewMockGophprofileService creates a new mock instance.
func NewMockGophprofileService(ctrl *gomock.Controller) *MockGophprofileService {
	mock := &MockGophprofileService{ctrl: ctrl}
	mock.recorder = &MockGophprofileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophprofileService) EXPECT() *MockGophprofileServiceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockGophprofileService) CreateUser(ctx context.Context, request domain.UserRegisterRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophprofileServiceMockRecorder) CreateUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophprofileService)(nil).CreateUser), ctx, request)
}

// FileStoragePing mocks base method.
func (m *MockGophprofileService) FileStoragePing(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileStoragePing", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FileStoragePing indicates an expected call of FileStoragePing.
func (mr *MockGophprofileServiceMockRecorder) FileStoragePing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileStoragePing", reflect.TypeOf((*MockGophprofileService)(nil).FileStoragePing), ctx)
}

// LoginUser mocks base method.
func (m *MockGophprofileService) LoginUser(ctx context.Context, request domain.UserLoginRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockGophprofileServiceMockRecorder) LoginUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockGophprofileService)(nil).LoginUser), ctx, request)
}

// Ping mocks base method.
func (m *MockGophprofileService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophprofileServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophprofileService)(nil).Ping), ctx)
}
