// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Vla8islav/gophprofile/internal/domain (interfaces: GophprofileRepository,GophprofileService,FileStorage,EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=domain_mock.go -package=mocks github.com/Vla8islav/gophprofile/internal/domain GophprofileRepository,GophprofileService,FileStorage,EventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/Vla8islav/gophprofile/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockGophprofileRepository is a mock of GophprofileRepository interface.
type MockGophprofileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGophprofileRepositoryMockRecorder
	isgomock struct{}
}

// MockGophprofileRepositoryMockRecorder is the mock recorder for MockGophprofileRepository.
type MockGophprofileRepositoryMockRecorder struct {
	mock *MockGophprofileRepository
}

// NewMockGophprofileRepository creates a new mock instance.
func NewMockGophprofileRepository(ctrl *gomock.Controller) *MockGophprofileRepository {
	mock := &MockGophprofileRepository{ctrl: ctrl}
	mock.recorder = &MockGophprofileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophprofileRepository) EXPECT() *MockGophprofileRepositoryMockRecorder {
	return m.recorder
}

// CreateAvatar mocks base method.
func (m *MockGophprofileRepository) CreateAvatar(ctx context.Context, params domain.CreateAvatarParams) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvatar", ctx, params)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAvatar indicates an expected call of CreateAvatar.
func (mr *MockGophprofileRepositoryMockRecorder) CreateAvatar(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvatar", reflect.TypeOf((*MockGophprofileRepository)(nil).CreateAvatar), ctx, params)
}

// CreateUser mocks base method.
func (m *MockGophprofileRepository) CreateUser(ctx context.Context, user domain.CreateUserParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophprofileRepositoryMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophprofileRepository)(nil).CreateUser), ctx, user)
}

// GetAvatarByID mocks base method.
func (m *MockGophprofileRepository) GetAvatarByID(ctx context.Context, avatarID string) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarByID", ctx, avatarID)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarByID indicates an expected call of GetAvatarByID.
func (mr *MockGophprofileRepositoryMockRecorder) GetAvatarByID(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarByID", reflect.TypeOf((*MockGophprofileRepository)(nil).GetAvatarByID), ctx, avatarID)
}

// GetLatestAvatarByUserID mocks base method.
func (m *MockGophprofileRepository) GetLatestAvatarByUserID(ctx context.Context, userID int64) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestAvatarByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestAvatarByUserID indicates an expected call of GetLatestAvatarByUserID.
func (mr *MockGophprofileRepositoryMockRecorder) GetLatestAvatarByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestAvatarByUserID", reflect.TypeOf((*MockGophprofileRepository)(nil).GetLatestAvatarByUserID), ctx, userID)
}

// GetUserByLogin mocks base method.
func (m *MockGophprofileRepository) GetUserByLogin(ctx context.Context, login string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, login)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockGophprofileRepositoryMockRecorder) GetUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockGophprofileRepository)(nil).GetUserByLogin), ctx, login)
}

// ListAvatarsByUserID mocks base method.
func (m *MockGophprofileRepository) ListAvatarsByUserID(ctx context.Context, userID int64) ([]domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvatarsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvatarsByUserID indicates an expected call of ListAvatarsByUserID.
func (mr *MockGophprofileRepositoryMockRecorder) ListAvatarsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvatarsByUserID", reflect.TypeOf((*MockGophprofileRepository)(nil).ListAvatarsByUserID), ctx, userID)
}

// Ping mocks base method.
func (m *MockGophprofileRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophprofileRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophprofileRepository)(nil).Ping), ctx)
}

// SetAvatarUploadStatus mocks base method.
func (m *MockGophprofileRepository) SetAvatarUploadStatus(ctx context.Context, avatarID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAvatarUploadStatus", ctx, avatarID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAvatarUploadStatus indicates an expected call of SetAvatarUploadStatus.
func (mr *MockGophprofileRepositoryMockRecorder) SetAvatarUploadStatus(ctx, avatarID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAvatarUploadStatus", reflect.TypeOf((*MockGophprofileRepository)(nil).SetAvatarUploadStatus), ctx, avatarID, status)
}

// SoftDeleteAvatar mocks base method.
func (m *MockGophprofileRepository) SoftDeleteAvatar(ctx context.Context, avatarID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteAvatar", ctx, avatarID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteAvatar indicates an expected call of SoftDeleteAvatar.
func (mr *MockGophprofileRepositoryMockRecorder) SoftDeleteAvatar(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteAvatar", reflect.TypeOf((*MockGophprofileRepository)(nil).SoftDeleteAvatar), ctx, avatarID)
}

// MockGophprofileService is a mock of GophprofileService interface.
type MockGophprofileService struct {
	ctrl     *gomock.Controller
	recorder *MockGophprofileServiceMockRecorder
	isgomock struct{}
}

// MockGophprofileServiceMockRecorder is the mock recorder for MockGophprofileService.
type MockGophprofileServiceMockRecorder struct {
	mock *MockGophprofileService
}

// NewMockGophprofileService creates a new mock instance.
func NewMockGophprofileService(ctrl *gomock.Controller) *MockGophprofileService {
	mock := &MockGophprofileService{ctrl: ctrl}
	mock.recorder = &MockGophprofileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGophprofileService) EXPECT() *MockGophprofileServiceMockRecorder {
	return m.recorder
}

// BrokerPing mocks base method.
func (m *MockGophprofileService) BrokerPing(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BrokerPing", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// BrokerPing indicates an expected call of BrokerPing.
func (mr *MockGophprofileServiceMockRecorder) BrokerPing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BrokerPing", reflect.TypeOf((*MockGophprofileService)(nil).BrokerPing), ctx)
}

// CreateUser mocks base method.
func (m *MockGophprofileService) CreateUser(ctx context.Context, request domain.UserRegisterRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGophprofileServiceMockRecorder) CreateUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGophprofileService)(nil).CreateUser), ctx, request)
}

// DeleteAvatar mocks base method.
func (m *MockGophprofileService) DeleteAvatar(ctx context.Context, avatarID string, requesterID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, avatarID, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockGophprofileServiceMockRecorder) DeleteAvatar(ctx, avatarID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockGophprofileService)(nil).DeleteAvatar), ctx, avatarID, requesterID)
}

// DeleteUserAvatar mocks base method.
func (m *MockGophprofileService) DeleteUserAvatar(ctx context.Context, userID, requesterID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAvatar", ctx, userID, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserAvatar indicates an expected call of DeleteUserAvatar.
func (mr *MockGophprofileServiceMockRecorder) DeleteUserAvatar(ctx, userID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAvatar", reflect.TypeOf((*MockGophprofileService)(nil).DeleteUserAvatar), ctx, userID, requesterID)
}

// FileStoragePing mocks base method.
func (m *MockGophprofileService) FileStoragePing(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileStoragePing", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FileStoragePing indicates an expected call of FileStoragePing.
func (mr *MockGophprofileServiceMockRecorder) FileStoragePing(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileStoragePing", reflect.TypeOf((*MockGophprofileService)(nil).FileStoragePing), ctx)
}

// GetAvatarContent mocks base method.
func (m *MockGophprofileService) GetAvatarContent(ctx context.Context, avatarID, sizeVariant string) (*domain.Avatar, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarContent", ctx, avatarID, sizeVariant)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAvatarContent indicates an expected call of GetAvatarContent.
func (mr *MockGophprofileServiceMockRecorder) GetAvatarContent(ctx, avatarID, sizeVariant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarContent", reflect.TypeOf((*MockGophprofileService)(nil).GetAvatarContent), ctx, avatarID, sizeVariant)
}

// GetAvatarMetadata mocks base method.
func (m *MockGophprofileService) GetAvatarMetadata(ctx context.Context, avatarID string) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarMetadata", ctx, avatarID)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarMetadata indicates an expected call of GetAvatarMetadata.
func (mr *MockGophprofileServiceMockRecorder) GetAvatarMetadata(ctx, avatarID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarMetadata", reflect.TypeOf((*MockGophprofileService)(nil).GetAvatarMetadata), ctx, avatarID)
}

// GetUserAvatarContent mocks base method.
func (m *MockGophprofileService) GetUserAvatarContent(ctx context.Context, userID int64, sizeVariant string) (*domain.Avatar, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAvatarContent", ctx, userID, sizeVariant)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserAvatarContent indicates an expected call of GetUserAvatarContent.
func (mr *MockGophprofileServiceMockRecorder) GetUserAvatarContent(ctx, userID, sizeVariant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAvatarContent", reflect.TypeOf((*MockGophprofileService)(nil).GetUserAvatarContent), ctx, userID, sizeVariant)
}

// ListUserAvatars mocks base method.
func (m *MockGophprofileService) ListUserAvatars(ctx context.Context, userID int64) ([]domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserAvatars", ctx, userID)
	ret0, _ := ret[0].([]domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserAvatars indicates an expected call of ListUserAvatars.
func (mr *MockGophprofileServiceMockRecorder) ListUserAvatars(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserAvatars", reflect.TypeOf((*MockGophprofileService)(nil).ListUserAvatars), ctx, userID)
}

// LoginUser mocks base method.
func (m *MockGophprofileService) LoginUser(ctx context.Context, request domain.UserLoginRequest) (*domain.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, request)
	ret0, _ := ret[0].(*domain.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockGophprofileServiceMockRecorder) LoginUser(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockGophprofileService)(nil).LoginUser), ctx, request)
}

// Ping mocks base method.
func (m *MockGophprofileService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGophprofileServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGophprofileService)(nil).Ping), ctx)
}

// UploadAvatar mocks base method.
func (m *MockGophprofileService) UploadAvatar(ctx context.Context, userID int64, fileName, mimeType string, size int64, content io.Reader) (*domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, fileName, mimeType, size, content)
	ret0, _ := ret[0].(*domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockGophprofileServiceMockRecorder) UploadAvatar(ctx, userID, fileName, mimeType, size, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockGophprofileService)(nil).UploadAvatar), ctx, userID, fileName, mimeType, size, content)
}

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
	isgomock struct{}
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFileStorage) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileStorageMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFileStorage)(nil).Delete), ctx, key)
}

// Download mocks base method.
func (m *MockFileStorage) Download(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockFileStorageMockRecorder) Download(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockFileStorage)(nil).Download), ctx, key)
}

// Ping mocks base method.
func (m *MockFileStorage) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockFileStorageMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockFileStorage)(nil).Ping), ctx)
}

// Upload mocks base method.
func (m *MockFileStorage) Upload(ctx context.Context, key, contentType string, size int64, content io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, contentType, size, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockFileStorageMockRecorder) Upload(ctx, key, contentType, size, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFileStorage)(nil).Upload), ctx, key, contentType, size, content)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventPublisher)(nil).Close))
}

// Ping mocks base method.
func (m *MockEventPublisher) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockEventPublisherMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockEventPublisher)(nil).Ping), ctx)
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, key, eventType string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, key, eventType, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, key, eventType, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, key, eventType, payload)
}
