package domain

import (
	"fmt"
	"time"
)

const (
	UploadStatusUploading = "uploading"
	UploadStatusCompleted = "completed"

	ProcessingStatusPending   = "pending"
	ProcessingStatusCompleted = "completed"
	ProcessingStatusFailed    = "failed"
)

// ThumbnailSizes maps the public size variant to its pixel edge. Thumbnails
// are square (scale-to-fill + center crop) and always JPEG.
var ThumbnailSizes = map[string]int{
	"100x100": 100,
	"300x300": 300,
}

// ThumbnailS3Key is where the worker stores a generated thumbnail.
func ThumbnailS3Key(avatarID, size string) string {
	return fmt.Sprintf("thumbnails/%s/%s.jpg", avatarID, size)
}

// ContentFor resolves which S3 object and content type a size variant is
// served with. Thumbnails are always JPEG regardless of the original's
// format; a variant without a generated thumbnail falls back to the
// original (thumbnails appear asynchronously).
func (a *Avatar) ContentFor(sizeVariant string) (s3Key, contentType string) {
	if sizeVariant == "" || sizeVariant == "original" {
		return a.S3Key, a.MimeType
	}
	if key, ok := a.ThumbnailS3Keys[sizeVariant]; ok {
		return key, "image/jpeg"
	}
	return a.S3Key, a.MimeType
}

// AllowedAvatarMimeTypes are the formats accepted on upload (validated by magic bytes).
var AllowedAvatarMimeTypes = map[string]bool{
	"image/jpeg": true,
	"image/png":  true,
	"image/webp": true,
}

const MaxAvatarSizeBytes = 10 << 20 // 10 MB

type Avatar struct {
	ID               string
	UserID           int64
	FileName         string
	MimeType         string
	SizeBytes        int64
	S3Key            string
	ThumbnailS3Keys  map[string]string // "100x100" > "thumbnails/<id>/100x100.jpg"
	UploadStatus     string
	ProcessingStatus string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type CreateAvatarParams struct {
	ID        string // UUID generated by the caller
	UserID    int64
	FileName  string
	MimeType  string
	SizeBytes int64
	S3Key     string
}

type AvatarUploadResponse struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	URL       string    `json:"url"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type ThumbnailInfo struct {
	Size string `json:"size"`
	URL  string `json:"url"`
}

type AvatarMetadataResponse struct {
	ID         string          `json:"id"`
	UserID     int64           `json:"user_id"`
	FileName   string          `json:"file_name"`
	MimeType   string          `json:"mime_type"`
	Size       int64           `json:"size"`
	Status     string          `json:"status"`
	Thumbnails []ThumbnailInfo `json:"thumbnails"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type AvatarListResponse struct {
	Avatars []AvatarMetadataResponse `json:"avatars"`
}

// AvatarURL is the public download path for an avatar; also used as the
// "url" field in API responses so clients never see raw S3 keys.
func AvatarURL(avatarID string) string {
	return "/api/v1/avatars/" + avatarID
}

func (a *Avatar) ToMetadataResponse() AvatarMetadataResponse {
	thumbs := make([]ThumbnailInfo, 0, len(a.ThumbnailS3Keys))
	for size := range a.ThumbnailS3Keys {
		thumbs = append(thumbs, ThumbnailInfo{
			Size: size,
			URL:  AvatarURL(a.ID) + "?size=" + size,
		})
	}
	return AvatarMetadataResponse{
		ID:         a.ID,
		UserID:     a.UserID,
		FileName:   a.FileName,
		MimeType:   a.MimeType,
		Size:       a.SizeBytes,
		Status:     a.ProcessingStatus,
		Thumbnails: thumbs,
		CreatedAt:  a.CreatedAt,
		UpdatedAt:  a.UpdatedAt,
	}
}
